CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(40) UNIQUE NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(100) NOT NULL, email varchar(255) UNIQUE NOT NULL, password_hash text NOT NULL, status varchar(20) NOT NULL DEFAULT 'ACTIVE', email_verified_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz);
CREATE INDEX users_email_idx ON users(email); CREATE INDEX users_deleted_at_idx ON users(deleted_at);
CREATE TABLE user_roles (user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, role_id uuid NOT NULL REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id,role_id));
CREATE TABLE refresh_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash char(64) UNIQUE NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX refresh_tokens_hash_idx ON refresh_tokens(token_hash);
CREATE TABLE products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(160) NOT NULL, sku varchar(80) UNIQUE NOT NULL, description text, price numeric(12,2) NOT NULL CHECK(price>=0), stock integer NOT NULL DEFAULT 0 CHECK(stock>=0), status varchar(20) NOT NULL DEFAULT 'ACTIVE', created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz); CREATE INDEX products_sku_idx ON products(sku); CREATE INDEX products_status_idx ON products(status); CREATE INDEX products_deleted_at_idx ON products(deleted_at);
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), action varchar(100) NOT NULL, resource varchar(100) NOT NULL, resource_id uuid, request_id uuid, ip inet, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE application_settings (key varchar(100) PRIMARY KEY, value jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
